name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12
          env:
            Heroku_Username: ${{ secrets.Heroku_Username }}
            Heroku_API_KEY: ${{ secrets.Heroku_API_KEY }}
            APP_NAME: ${{ secrets.Heroku_APP_NAME }}
          with:
            heroku_api_key: $Heroku_API_KEY
            heroku_email: $Heroku_Username
            heroku_app_name: $APP_NAME
            branch: main
            dontautocreate: true
            usedocker: true
            docker_heroku_process_type: web
            region: eu
            stack: container